[package]
name = "calib"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
sim = { workspace = true }
geom = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
rayon = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
extract = { workspace = true }
