[package]
name = "cs2mod-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lints]
workspace = true

[[bin]]
name = "cs2mod"
path = "src/main.rs"

[dependencies]
s2fmt = { workspace = true }
geom = { workspace = true }
extract = { workspace = true }
sim = { workspace = true }
solver = { workspace = true }
calib = { workspace = true }
server = { workspace = true }
radar = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { version = "1", features = ["rt-multi-thread"] }
