//! Golden-fixture replay tests: bit-exact regression fixtures generated by
//! the ACTUAL compiled reference (via `cs_sim`, the cross-check harness kept
//! in `D:\porject\modulator-work\scratch\{cs_sim,sim_crosscheck}`, NOT
//! checked into this repo), not game files and not our own Rust output.
//! `synthetic_room_golden.json` replays against a small in-test box-room
//! mesh (always runs); `de_mirage_golden.json` replays against the real map
//! (`#[ignore]`, needs `CS2MOD_CGEO`).
//!
//! Goldens were generated by the reference C# on Windows, where f32
//! `sin`/`cos` come from the MSVC CRT; our Rust matches that bit-exactly on
//! `cfg(windows)` (also MSVC CRT). On other platforms (e.g. Linux/glibc),
//! `sinf`/`cosf` can round differently from MSVC in rare cases, so `rest`
//! and `first_touch` are compared within a small tolerance and
//! `flight_time` within one tick there instead of bit-exactly. `bounces`,
//! `lost` and `glass_breaks` are always exact everywhere, since they are
//! integer/boolean outcomes that don't depend on trig rounding.

use geom::filter::grenade_mask;
use geom::grid::UniformGrid;
use geom::math::{Aabb, V3};
use geom::mesh::{CollisionAttribute, CollisionMesh, MeshObject, ObjectKind, SurfaceProperty};
use serde::Deserialize;
use sim::{ThrowConstants, ThrowSpec, ThrowType, Trace, simulate_exact};

#[derive(Deserialize)]
struct GoldenEntry {
    eye: [f32; 3],
    yaw_deg: f32,
    pitch_deg: f32,
    throw_type: u8,
    strength: f32,
    run_yaw_offset_deg: f32,
    rest: [f32; 3],
    bounces: u32,
    flight_time: f32,
    lost: bool,
    glass_breaks: u32,
    first_touch: Option<[f32; 3]>,
}

fn throw_type_from_byte(b: u8) -> ThrowType {
    match b {
        0 => ThrowType::Stand,
        1 => ThrowType::Crouch,
        2 => ThrowType::JumpThrow,
        3 => ThrowType::CrouchJumpThrow,
        4 => ThrowType::RunJumpThrow,
        other => panic!("unknown throw_type byte {other}"),
    }
}

/// Per-component tolerance for `rest`/`first_touch` on non-Windows targets,
/// where libm `sinf`/`cosf` can round differently from the MSVC CRT that
/// generated the goldens.
#[cfg(not(windows))]
const POSITION_TOLERANCE: f32 = 0.01;

/// One tick (64 ticks/s) tolerance for `flight_time` on non-Windows targets.
#[cfg(not(windows))]
const FLIGHT_TIME_TOLERANCE: f32 = 1.0 / 64.0;

#[cfg(windows)]
fn assert_position_close(actual: [f32; 3], expected: [f32; 3], what: &str, i: usize) {
    assert_eq!(actual, expected, "entry {i}: {what} mismatch");
}

#[cfg(not(windows))]
fn assert_position_close(actual: [f32; 3], expected: [f32; 3], what: &str, i: usize) {
    for c in 0..3 {
        let diff = (actual[c] - expected[c]).abs();
        assert!(
            diff <= POSITION_TOLERANCE,
            "entry {i}: {what} mismatch at component {c}: got {actual:?}, want {expected:?} \
             (diff {diff} > tolerance {POSITION_TOLERANCE})"
        );
    }
}

#[cfg(windows)]
fn assert_flight_time_close(actual: f32, expected: f32, i: usize) {
    assert_eq!(actual, expected, "entry {i}: flight_time mismatch");
}

#[cfg(not(windows))]
fn assert_flight_time_close(actual: f32, expected: f32, i: usize) {
    let diff = (actual - expected).abs();
    assert!(
        diff <= FLIGHT_TIME_TOLERANCE,
        "entry {i}: flight_time mismatch: got {actual}, want {expected} \
         (diff {diff} > tolerance {FLIGHT_TIME_TOLERANCE})"
    );
}

fn replay(grid: &UniformGrid, entries: &[GoldenEntry]) {
    let k = ThrowConstants::default();
    for (i, e) in entries.iter().enumerate() {
        let spec = ThrowSpec {
            eye: V3::from_array(e.eye),
            yaw_deg: e.yaw_deg,
            pitch_deg: e.pitch_deg,
            throw_type: throw_type_from_byte(e.throw_type),
            strength: e.strength,
            run_yaw_offset_deg: e.run_yaw_offset_deg,
        };
        let r = simulate_exact(grid, &spec, &k, Trace::default());
        assert_position_close(r.rest.to_array(), e.rest, "rest", i);
        assert_eq!(r.bounces, e.bounces, "entry {i}: bounces mismatch");
        assert_flight_time_close(r.flight_time, e.flight_time, i);
        assert_eq!(r.lost, e.lost, "entry {i}: lost mismatch");
        assert_eq!(
            r.glass_breaks, e.glass_breaks,
            "entry {i}: glass_breaks mismatch"
        );
        match (r.first_touch, e.first_touch) {
            (Some(a), Some(b)) => assert_position_close(a.to_array(), b, "first_touch", i),
            (None, None) => {}
            (a, b) => panic!("entry {i}: first_touch mismatch: got {a:?}, want {b:?}"),
        }
    }
}

/// Margin added past the room's own bounds before building the collider
/// region: this room's walls are all exactly flush with its own bounding
/// box (a literal box), so an unpadded region would trip the reference's
/// documented one-sided-clamp region bug (`geom::grid::UniformGrid::build`'s
/// rustdoc) on every outer wall, unlike organic real-map geometry where this
/// only ever affects a handful of boundary-flush triangles. Must match
/// `sim_crosscheck/src/export_synth.rs`'s `ROOM_PAD` (outside this repo),
/// which generated `synthetic_room_golden.json` with this same padding.
const ROOM_PAD: f32 = 32.0;

/// A 512x512x384 box room centred on the origin: floor (z=0), ceiling
/// (z=384), solid walls at x=-256/y=-256/y=256, and one breakable wall at
/// x=256. Kept byte-for-byte identical to the generator's own copy in
/// `sim_crosscheck/src/export_synth.rs` (outside this repo), so the fixture
/// this test replays was generated against exactly this geometry.
fn synthetic_room_mesh() -> CollisionMesh {
    let mut mesh = CollisionMesh::new();
    let solid = mesh
        .add_attribute(CollisionAttribute {
            name: "Default".to_string(),
            interact_as: vec![],
            interact_with: vec![],
            interact_exclude: vec![],
            synthetic: false,
        })
        .unwrap();
    let breakable = mesh
        .add_attribute(CollisionAttribute {
            name: "EntityBreakable".to_string(),
            interact_as: vec![],
            interact_with: vec![],
            interact_exclude: vec![],
            synthetic: false,
        })
        .unwrap();
    let obj = mesh.add_object(MeshObject {
        kind: ObjectKind::WorldMesh,
        classname: None,
        targetname: None,
        model: None,
        hammer_id: None,
        source_index: 0,
        hull_flags: None,
    });
    let quad = |mesh: &mut CollisionMesh, verts: [[f32; 3]; 4], attr: u16| {
        mesh.push_triangles(
            &verts,
            &[[0, 1, 2], [0, 2, 3]],
            attr,
            |_| SurfaceProperty::NONE,
            obj,
        )
        .unwrap();
    };
    quad(
        &mut mesh,
        [
            [-256.0, -256.0, 0.0],
            [256.0, -256.0, 0.0],
            [256.0, 256.0, 0.0],
            [-256.0, 256.0, 0.0],
        ],
        solid,
    );
    quad(
        &mut mesh,
        [
            [-256.0, -256.0, 384.0],
            [256.0, -256.0, 384.0],
            [256.0, 256.0, 384.0],
            [-256.0, 256.0, 384.0],
        ],
        solid,
    );
    quad(
        &mut mesh,
        [
            [-256.0, -256.0, 0.0],
            [-256.0, 256.0, 0.0],
            [-256.0, 256.0, 384.0],
            [-256.0, -256.0, 384.0],
        ],
        solid,
    );
    quad(
        &mut mesh,
        [
            [-256.0, -256.0, 0.0],
            [256.0, -256.0, 0.0],
            [256.0, -256.0, 384.0],
            [-256.0, -256.0, 384.0],
        ],
        solid,
    );
    quad(
        &mut mesh,
        [
            [-256.0, 256.0, 0.0],
            [256.0, 256.0, 0.0],
            [256.0, 256.0, 384.0],
            [-256.0, 256.0, 384.0],
        ],
        solid,
    );
    quad(
        &mut mesh,
        [
            [256.0, -256.0, 0.0],
            [256.0, 256.0, 0.0],
            [256.0, 256.0, 384.0],
            [256.0, -256.0, 384.0],
        ],
        breakable,
    );
    mesh
}

#[test]
fn synthetic_room_golden_replay() {
    let mesh = synthetic_room_mesh();
    let mask = grenade_mask(&mesh);
    let unpadded = geom::collider::ColliderTriangles::build(&mesh, &mask, None)
        .unwrap()
        .bounds()
        .unwrap();
    let region = Aabb {
        min: unpadded.min - V3::new(ROOM_PAD, ROOM_PAD, ROOM_PAD),
        max: unpadded.max + V3::new(ROOM_PAD, ROOM_PAD, ROOM_PAD),
    };
    let grid = UniformGrid::build(&mesh, &mask, Some(region), 128.0).unwrap();
    let json = include_str!("fixtures/synthetic_room_golden.json");
    let entries: Vec<GoldenEntry> = serde_json::from_str(json).unwrap();
    assert!(!entries.is_empty());
    replay(&grid, &entries);
}

#[test]
#[ignore = "needs CS2MOD_CGEO"]
fn de_mirage_golden_replay() {
    let cgeo_path = std::env::var("CS2MOD_CGEO")
        .expect("set CS2MOD_CGEO=<path to world.cgeo> to run this test");
    let (mesh, _meta) = geom::cgeo::load_cgeo(&cgeo_path).expect("failed to load world.cgeo");
    let mask = grenade_mask(&mesh);
    let grid = UniformGrid::build(&mesh, &mask, None, 128.0).unwrap();
    let json = include_str!("fixtures/de_mirage_golden.json");
    let entries: Vec<GoldenEntry> = serde_json::from_str(json).unwrap();
    assert!(!entries.is_empty());
    replay(&grid, &entries);
}
