//! Smoke golden-fixture replay: bit-exact regression fixtures generated by
//! the ACTUAL compiled reference (`cs_smoke_golden`, kept outside this repo
//! in `D:\porject\modulator-work\scratch\cs_smoke_golden`, driving
//! `SmokeFloodFill.Fill`/`Occlusion.Test` directly), not our own Rust
//! output. `synthetic_room_smoke_golden.json` replays against a small
//! in-test box-room mesh (always runs); `de_mirage_smoke_golden.json`
//! replays against the real map (`#[ignore]`, needs `CS2MOD_CGEO`).
//!
//! Both fixtures were generated with the voxel grid built over the
//! `"Default,default"` collision-attribute names mask (`meta.attribute_filter`
//! in each fixture file) - the reference's own documented smoke/voxel
//! invocations (`MeshSetup.SingleTargetDefaultAttrs` minus `EntitySolid`),
//! NOT the grenade-flight mask `crates/sim/tests/golden.rs` uses. On the
//! synthetic room this deliberately excludes the breakable wall (attribute
//! `EntityBreakable`) from the smoke voxel grid, so smoke escapes through
//! it - itself a check that the mask is actually applied.

use std::ops::ControlFlow;

use geom::filter::names_mask;
use geom::math::V3;
use geom::mesh::{CollisionAttribute, CollisionMesh, MeshObject, ObjectKind, SurfaceProperty};
use geom::voxel::VoxelGrid;
use serde::Deserialize;
use sim::{SmokeParams, smoke_fill};

#[derive(Deserialize)]
struct Probe {
    angle_bits: u32,
    smoke_cells_crossed: u32,
    geometry_blocked: bool,
}

#[derive(Deserialize)]
struct Entry {
    rest: [f32; 3],
    preset: String,
    cell_count: u32,
    cell_hash: String,
    out_of_bounds: bool,
    occlusion: Vec<Probe>,
}

#[derive(Deserialize)]
struct Meta {
    attribute_filter: String,
    voxel_size: f32,
}

#[derive(Deserialize)]
struct Fixture {
    meta: Meta,
    entries: Vec<Entry>,
}

fn preset_by_name(name: &str) -> SmokeParams {
    match name {
        "UncalibratedDefault" => SmokeParams::UNCALIBRATED_DEFAULT,
        "Coverage" => SmokeParams::COVERAGE,
        "FullReach" => SmokeParams::FULL_REACH,
        "Conservative" => SmokeParams::CONSERVATIVE,
        other => panic!("unknown preset {other}"),
    }
}

/// FNV-1a 64-bit over each cell index's 4 little-endian bytes, in fill
/// order. Not a reference algorithm - our own compact stand-in for checking
/// the reference's own cell ORDER without checking in a multi-thousand-entry
/// cell list per fixture row (matches `cs_smoke_golden`'s `Fnv1a64`).
fn fnv1a64(cells: &[u32]) -> u64 {
    const OFFSET: u64 = 0xcbf29ce484222325;
    const PRIME: u64 = 0x100000001b3;
    let mut h = OFFSET;
    for &c in cells {
        for b in c.to_le_bytes() {
            h ^= b as u64;
            h = h.wrapping_mul(PRIME);
        }
    }
    h
}

fn replay(grid: &VoxelGrid, fixture: &Fixture) {
    assert_eq!(fixture.meta.attribute_filter, "Default,default");
    assert_eq!(fixture.meta.voxel_size, 16.0);
    for (i, e) in fixture.entries.iter().enumerate() {
        let rest = V3::from_array(e.rest);
        let preset = preset_by_name(&e.preset);
        let result = smoke_fill(grid, rest, &preset);
        if e.out_of_bounds {
            assert!(result.is_err(), "entry {i}: expected out-of-bounds error");
            continue;
        }
        let volume = result.unwrap_or_else(|err| panic!("entry {i}: {err}"));
        assert_eq!(
            volume.cells.len() as u32,
            e.cell_count,
            "entry {i}: cell count"
        );
        let hash = fnv1a64(&volume.cells);
        assert_eq!(
            hash.to_string(),
            e.cell_hash,
            "entry {i}: cell order (FNV hash)"
        );

        for (j, probe) in e.occlusion.iter().enumerate() {
            let ang = f32::from_bits(probe.angle_bits);
            let d = V3::new(300.0 * ang.cos(), 300.0 * ang.sin(), 0.0);
            let up = V3::new(0.0, 0.0, 40.0);
            let mut smoke_cells_crossed = 0u32;
            let mut geometry_blocked = false;
            grid.traverse(rest + up + d, rest + up - d, |index, _coords| {
                if grid.is_solid(index) {
                    geometry_blocked = true;
                } else if volume.contains(index as u32) {
                    smoke_cells_crossed += 1;
                }
                ControlFlow::Continue(())
            });
            assert_eq!(
                smoke_cells_crossed, probe.smoke_cells_crossed,
                "entry {i} probe {j}: smoke_cells_crossed"
            );
            assert_eq!(
                geometry_blocked, probe.geometry_blocked,
                "entry {i} probe {j}: geometry_blocked"
            );
        }
    }
}

/// Same 512x512x384 box room as `crates/sim/tests/golden.rs`'s
/// `synthetic_room_mesh` (kept independent on purpose: this test's voxel
/// grid uses a different attribute mask, so it does not need `golden.rs`'s
/// `ROOM_PAD` region-clamp workaround - `VoxelGrid::build`'s own symmetric,
/// bug-free per-triangle cell clamp has no reference-side region-boundary
/// deviation the way `UniformGrid`/`TriangleCollider` do).
fn synthetic_room_mesh() -> CollisionMesh {
    let mut mesh = CollisionMesh::new();
    let solid = mesh
        .add_attribute(CollisionAttribute {
            name: "Default".to_string(),
            interact_as: vec![],
            interact_with: vec![],
            interact_exclude: vec![],
            synthetic: false,
        })
        .unwrap();
    let breakable = mesh
        .add_attribute(CollisionAttribute {
            name: "EntityBreakable".to_string(),
            interact_as: vec![],
            interact_with: vec![],
            interact_exclude: vec![],
            synthetic: false,
        })
        .unwrap();
    let obj = mesh.add_object(MeshObject {
        kind: ObjectKind::WorldMesh,
        classname: None,
        targetname: None,
        model: None,
        hammer_id: None,
        source_index: 0,
        hull_flags: None,
    });
    let quad = |mesh: &mut CollisionMesh, verts: [[f32; 3]; 4], attr: u16| {
        mesh.push_triangles(
            &verts,
            &[[0, 1, 2], [0, 2, 3]],
            attr,
            |_| SurfaceProperty::NONE,
            obj,
        )
        .unwrap();
    };
    quad(
        &mut mesh,
        [
            [-256.0, -256.0, 0.0],
            [256.0, -256.0, 0.0],
            [256.0, 256.0, 0.0],
            [-256.0, 256.0, 0.0],
        ],
        solid,
    );
    quad(
        &mut mesh,
        [
            [-256.0, -256.0, 384.0],
            [256.0, -256.0, 384.0],
            [256.0, 256.0, 384.0],
            [-256.0, 256.0, 384.0],
        ],
        solid,
    );
    quad(
        &mut mesh,
        [
            [-256.0, -256.0, 0.0],
            [-256.0, 256.0, 0.0],
            [-256.0, 256.0, 384.0],
            [-256.0, -256.0, 384.0],
        ],
        solid,
    );
    quad(
        &mut mesh,
        [
            [-256.0, -256.0, 0.0],
            [256.0, -256.0, 0.0],
            [256.0, -256.0, 384.0],
            [-256.0, -256.0, 384.0],
        ],
        solid,
    );
    quad(
        &mut mesh,
        [
            [-256.0, 256.0, 0.0],
            [256.0, 256.0, 0.0],
            [256.0, 256.0, 384.0],
            [-256.0, 256.0, 384.0],
        ],
        solid,
    );
    quad(
        &mut mesh,
        [
            [256.0, -256.0, 0.0],
            [256.0, 256.0, 0.0],
            [256.0, 256.0, 384.0],
            [256.0, -256.0, 384.0],
        ],
        breakable,
    );
    mesh
}

#[test]
fn synthetic_room_smoke_golden_replay() {
    let mesh = synthetic_room_mesh();
    let mask = names_mask(&mesh, &["Default", "default"]);
    let region = geom::collider::ColliderTriangles::build(&mesh, &mask, None)
        .unwrap()
        .bounds()
        .unwrap();
    let grid = VoxelGrid::build(&mesh, &mask, 16.0, region).unwrap();
    let json = include_str!("fixtures/synthetic_room_smoke_golden.json");
    let fixture: Fixture = serde_json::from_str(json).unwrap();
    assert!(!fixture.entries.is_empty());
    replay(&grid, &fixture);
}

#[test]
#[ignore = "needs CS2MOD_CGEO"]
fn de_mirage_smoke_golden_replay() {
    let cgeo_path = std::env::var("CS2MOD_CGEO")
        .expect("set CS2MOD_CGEO=<path to world.cgeo> to run this test");
    let (mesh, _meta) = geom::cgeo::load_cgeo(&cgeo_path).expect("failed to load world.cgeo");
    let mask = names_mask(&mesh, &["Default", "default"]);
    let region = geom::collider::ColliderTriangles::build(&mesh, &mask, None)
        .unwrap()
        .bounds()
        .unwrap();
    let grid = VoxelGrid::build(&mesh, &mask, 16.0, region).unwrap();
    let json = include_str!("fixtures/de_mirage_smoke_golden.json");
    let fixture: Fixture = serde_json::from_str(json).unwrap();
    assert!(!fixture.entries.is_empty());
    replay(&grid, &fixture);
}
