// Every Russian UI string lives here, so a later pass never has to hunt through the other
// modules for text to fix (`s6f1_viewer_shell.md`: "русские строки — в одном месте").

// `POST /api/lineup`'s own `emptyReason` (`crates/solver/src/target.rs`) is English, server-side
// prose - never shown raw (round-3 review finding 7). Each pattern here is one of that file's own
// `empty_reason = Some(...)` sites (`target.rs:483` "cancelled", `:1133-1146` the unreachable-
// target message with its embedded coordinates, `:1829-1839` the three stand-spot reasons,
// including the pin-filtered-area one and the "none of the N stand spots..." one with its count).
const EMPTY_REASON_PATTERNS = [
  { re: /^cancelled$/, text: () => "Поиск отменён." },
  {
    re: /^target \([^)]*\) has no reachable landing cells/,
    text: () => "Цель недостижима - точка оказалась внутри геометрии, либо допуск слишком мал.",
  },
  {
    re: /^no corner\/wall stand spots in the chosen area$/,
    text: () => "В выбранной области нет точек у стены или в углу - ослабьте «Упор» или измените область.",
  },
  {
    re: /^no stand spots in range of that throw position/,
    text: () => "Рядом с точкой броска нет точек стояния - расширьте область или выберите точку на полу.",
  },
  {
    re: /^none of the (\d+) stand spots in range can land a smoke there$/,
    text: (m) => `Ни одна из ${m[1]} точек в радиусе не даёт нужного приземления.`,
  },
];

// Never falls through to the server's own English text - an unrecognised reason (a future server
// change, or one of these patterns drifting) gets a generic Russian line instead.
function translateEmptyReason(reason) {
  if (!reason) {
    return "";
  }
  for (const { re, text } of EMPTY_REASON_PATTERNS) {
    const m = re.exec(reason);
    if (m) {
      return text(m);
    }
  }
  return "Раскидок не нашлось. Попробуйте изменить параметры поиска.";
}

export const strings = {
  appTitle: "cs2-modulation",

  setup: {
    heading: "Первый запуск",
    intro: "Программа читает только файлы на диске и ничего не делает с запущенной игрой.",
    gameDirLabel: "Папка CS2",
    gameDirHint: "Подойдёт и корень установки, и путь вида ...\\game\\csgo",
    gameDirPlaceholder: "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Counter-Strike Global Offensive",
    checkButton: "Проверить",
    checking: "Проверяю...",
    gameDirAdjusted: (dir) => `Сохранён путь: ${dir}`,
    gameBuildFound: (build) => `Найден билд игры: ${build}`,
    cacheDirLabel: "Папка кэша (необязательно)",
    cacheDirHint: "Куда сохранять извлечённые данные карт; по умолчанию рядом с программой.",
    cacheDirPlaceholder: "оставьте пустым, чтобы использовать путь по умолчанию",
    saveCacheButton: "Сохранить",
    restartRequired: "Новый путь к кэшу заработает после перезапуска cs2mod serve.",
    cacheDirSaved: "Сохранено.",
    continueButton: "Продолжить",
  },

  maps: {
    heading: "Карты",
    backToSetup: "Настройки",
    staleNoGameDir: "кэш не сверен с установленной игрой",
    staleWrongBuild: "кэш от другого билда игры",
    reextractButton: "Переизвлечь",
    prepareButton: "Подготовить",
    cancelButton: "Отменить",
    openButton: "Открыть",
    noMaps: "Нет ни одной подготовленной карты.",
    extractNewLabel: "Добавить карту по имени",
    extractNamePlaceholder: "de_mirage",
    extractButton: "Извлечь",
    stageExtract: "извлечение",
    stageStandspots: "точки стояния",
    stageViewerdata: "радар",
    stageRender: "3D-модель",
    stageQueued: "в очереди",
    stageDone: "готово",
    renderPhases: { geometry: "геометрия", entities: "объекты", lighting: "освещение", skybox: "3D-небо", writing: "запись" },
    loading: "Загрузка карт...",
    statusReady: "Готово",
    status3dReady: "3D готово",
    statusNeedsPrepare: "Нужно подготовить",
    statusStale: "Кэш устарел",
    modeDe: "Обезвреживание",
    modeCs: "Заложники",
    modeAr: "Гонка вооружений",
  },

  mapScreen: {
    backToList: "‹ Карты",
    levelsHeading: "Несколько высот в этой точке - выберите нужную",
    levelUnnamed: "без названия",
    manualPlaceholder: "setpos x y z; setang pitch yaw 0",
    manualButton: "Применить",
    manualBad: "Не удалось разобрать строку setpos.",
    noFloorHere: "В этой точке нет пола - выберите другое место.",
    targetModeLabel: "Цель",
    targetModePoint: "Точка",
    targetModeArea: "Область",
    stepTarget: "Куда бросить",
    stepOrigin: "Откуда бросать",
    stepThrow: "Граната и бросок",
    targetHintPoint: "Клик по карте",
    targetHintArea: "Обведите область",
    targetRowClear: "Убрать цель",
    targetRowZ: (z) => `z ${z}`,
    originHintPoint: "Правый клик (2D) или Shift+клик (3D)",
    originRowClear: "Убрать точку броска",
    manualToggle: "Вставить из консоли",
    schemeToggle: "Схема",
    sectionDefault: "Обычный",
    sectionLower: "Нижний",
    sectionUpper: "Верхний",
  },

  solveParams: {
    heading: "Дополнительно",
    grenadeLabel: "Граната",
    grenadeSmoke: "Смок",
    grenadeFlash: "Вспышка",
    grenadeHe: "Осколочная",
    grenadeMolotov: "Зажигательная",
    grenadeDecoy: "Обманка",
    grenadeComingSoon: "скоро",
    grenadeOthersSoon: "Вспышки, осколочные, молотовы - скоро",
    scopeLabel: "Откуда бросать",
    scopeAll: "Карта",
    scopeSpawns: "Спавны",
    scopePointSeg: "Точка",
    scopeAreaSeg: "Область",
    originReachLabel: "Радиус",
    originPinLabel: "Упор",
    originPinAny: "Любой",
    originPinWallOrCorner: "У стены",
    originPinCornerOnly: "В углу",
    areaHint: "Обведите на карте область, откуда допустим бросок - клики ставят вершины, двойной клик/Enter/клик по первой вершине замыкает, Backspace убирает последнюю вершину, Esc отменяет.",
    targetAreaHint: "Обведите на карте область, куда должна упасть граната - клики ставят вершины, двойной клик/Enter/клик по первой вершине замыкает, Backspace убирает последнюю вершину, Esc отменяет.",
    areaDrawButton: "Обвести область",
    areaStopButton: "Остановить рисование",
    areaEditButton: "Редактировать область",
    areaDeleteButton: "Удалить область",
    areaStatus: (n) => `область: ${n} вершин`,
    areaZMinLabel: "от",
    areaZMaxLabel: "до",
    areaZHint: "Необязательно - для многоэтажных мест (например, только крыша).",
    areaLevelsLabel: "Этаж:",
    areaLevelTop: (z) => `верхний (${z})`,
    areaLevelBottom: (z) => `нижний (${z})`,
    areaLevelNth: (n, z) => `${n}-й этаж (${z})`,
    toleranceLabel: "Допуск, ед.",
    minStabilityLabel: "Мин. стабильность",
    fineScanLabel: "Подробный поиск",
    typesLabel: "Тип броска",
    typeStand: "Стоя",
    typeCrouch: "Присев",
    typeJumpThrow: "Прыжок",
    typeCrouchJumpThrow: "Присев + прыжок",
    strengthsLabel: "Клики",
    strength1: "ЛКМ",
    strengthHalf: "ЛКМ+ПКМ",
    strength0: "ПКМ",
    brokenLabel: "Разрушения",
    brokenGlass: "Стекло разбито",
    brokenDoors: "Двери открыты",
  },

  solve: {
    runButton: "Найти раскидки",
    cancelButton: "Отменить",
    needTarget: "Сначала выберите цель на карте.",
    needTypes: "Выберите хотя бы один тип броска.",
    needStrengths: "Выберите хотя бы один клик.",
    elapsed: (s) => `${s.toFixed(1).replace(".", ",")} с`,
    checkedCount: (n) => `проверено: ${n}`,
    verifiedCount: (n) => `найдено: ${n}`,
    cachedResult: "Ответ из кэша.",
    emptyHint: "Можно ослабить допуск или расширить область, откуда допустим бросок.",
    translateEmptyReason,
    phases: {
      queued: "в очереди",
      prepare: "подготовка",
      colliders: "подготовка коллизий",
      origins: "перебор позиций",
      "pinned-origins": "точки у стен",
      "after-pins": "после точек у стен",
      sweep: "перебор бросков",
      verify: "проверка кандидатов",
      exhaustive: "полный перебор",
      escalate: "уточнение",
      "escalate-fine": "точное уточнение",
      sightline: "проверка видимости",
      pins: "точки прицеливания",
      "progress-truncated": "поток точек урезан (слишком много)",
    },
  },

  panel: {
    heading: "Раскидки",
    count: (n) => `${n}`,
    sortLabel: "Сортировка",
    sortBest: "Лучшие",
    sortEasy: "Лёгкие сначала",
    sortFast: "Быстрые",
    stableOnly: "Только лёгкие",
    hiddenOnly: "Скрытые",
    typeAll: "Все типы",
    typeFilterLabel: "Фильтр по типу броска",
    positionFilterLabel: "Упор",
    positionAll: "Любой",
    positionWallOrCorner: "У стены",
    positionCornerOnly: "В углу",
    filtersButton: "Фильтры",
    filtersButtonActive: (n) => `Фильтры · ${n}`,
    filtersClose: "Закрыть фильтры",
    removeFilter: "Убрать фильтр",
    toTarget: (n) => `до цели ${n} ед.`,
    distance: "расстояние",
    insideArea: "в области",
    stability: "стабильность",
    humanError: "погрешность",
    bounces: "отскоков",
    flightTime: "время полёта",
    pinCorner: "Упор в угол",
    pinWall: "У стены",
    exposedYes: "виден",
    exposedNo: "скрыт",
    copyButton: "Скопировать",
    copied: "Скопировано",
    copyFallback: "Строка выделена - нажмите Ctrl+C.",
    emptyReasonPrefix: "Ничего не найдено",
    emptyNoResultsTitle: "Пока нет раскидок",
    emptyNoResultsHint: "Поставьте цель и нажмите «Найти раскидки».",
    searchingTitle: "Идёт поиск...",
    searchingHint: "Раскидки появятся здесь, как только найдутся.",
    emptyFilteredTitle: "Ничего не подходит под фильтры",
    emptyFilteredHint: "Попробуйте ослабить фильтры ниже.",
    resetFilters: "Сбросить фильтры",
    difficultyEasy: "Лёгкая",
    difficultyMedium: "Средняя",
    difficultyHard: "Сложная",
    moreButton: "Подробнее",
    lessButton: "Свернуть",
    detailsFeet: "Точка броска",
    detailsRest: "Точка приземления",
    detailsAim: "Ориентир прицела",
    detailsHumanError: (n) => `Разброс при неточном прицеле ≈ ${n} ед.`,
    detailsExact: "Точная команда",
    aimSky: "в небо - чёткого ориентира нет, наводьтесь как в «Вид игрока»",
    aimEdge: "на край объекта, видимый в прицеле",
    aimReticle: "на объект прямо под прицелом",
    aimFlat: "ориентира нет - используйте «Вид игрока» и координаты",
    warnGlass: (n) => `Пролетает сквозь стекло (${n}) - если оно разбито, точка приземления другая.`,
    warnStateDependent: "Результат зависит от состояния карты (открытых дверей или разбитого стекла).",
    instructionStandCorner: "Встаньте в угол (упор) - точка на карте",
    instructionStandWall: "Встаньте у стены (упор) - точка на карте",
    instructionStandOpen: "Встаньте в отмеченную точку на карте",
    instructionCrouch: "Присядьте (Ctrl)",
    instructionAim: "Наведите прицел как в «Вид игрока»",
    instructionThrowJump: (click) => `Зажмите ${click}, нажмите прыжок и сразу отпустите ${click}`,
    instructionThrowJumpBoth: "Зажмите ЛКМ и ПКМ, нажмите прыжок и сразу отпустите обе",
    instructionThrowClick: (click) => `Нажмите ${click}`,
    instructionThrowBoth: "Зажмите ЛКМ и ПКМ и отпустите обе",
    clickLeft: "ЛКМ",
    clickBoth: "ЛКМ+ПКМ",
    clickRight: "ПКМ",
    typeUnknown: "Другое",
    clickUnknown: "клик",
  },

  gallery: {
    aimTitle: "Прицел",
    standTitle: "Позиция",
    landTitle: "Приземление",
    unsupportedBlock: "Откройте 3D, чтобы увидеть прицел",
    showIn3d: "Показать в 3D",
    lightboxClose: "Закрыть",
    loading: "Рендерю...",
  },

  view3d: {
    toggle2d: "2D",
    toggle3d: "3D",
    loading: (percent) => (percent != null ? `Загрузка модели: ${percent}%` : "Загрузка модели..."),
    loadError: "Не удалось загрузить 3D-модель карты.",
    noRender: "Для этой карты ещё не готова текстурованная 3D-модель.",
    renderOutdated: "3D-модель этой карты устарела и требует пересборки.",
    prepareButton: "Подготовить 3D",
    modeFly: "Полёт",
    modeOrbit: "Облёт",
    collisionsOn: "Показать коллизии",
    collisionsOff: "Скрыть коллизии",
    flyHint: "WASD - движение, ПКМ - смотреть, ЛКМ - цель, Shift+ЛКМ - точка броска, Shift - быстрее, Space/Ctrl - вверх/вниз, колесо - скорость.",
    areaDrawHint: "ЛКМ - поставить вершину, клик по первой вершине/двойной клик/Enter - замкнуть область, Backspace - убрать вершину, Esc - отменить рисование.",
    areaDraftDiscarded: "Незаконченная область сброшена при переключении вида.",
    lightingGame: "Освещение: игровое",
    lightingSimple: "Освещение: простое",
    lightingUnavailable: "Игровое освещение недоступно для этой карты (нет данных F3a-4).",
  },

  fpv: {
    button: "Вид игрока",
    exitButton: "Выйти (Esc)",
    exitHint: "Esc или кнопка - выход из вида игрока.",
    notReady: "Сначала переключитесь на 3D и дождитесь загрузки модели.",
    copyButton: "Скопировать setpos/setang",
  },

  errors: {
    serverDown: "Сервер cs2mod serve не отвечает.",
    streamBroken: "Соединение с задачей прервалось. Переподключиться?",
    reconnectButton: "Переподключиться",
    retryButton: "Повторить",
    genericPrefix: "Ошибка",
  },

  theme: {
    toggleToDark: "Тёмная тема",
    toggleToLight: "Светлая тема",
  },

};
