// Every Russian UI string lives here, so a later pass never has to hunt through the other
// modules for text to fix (`s6f1_viewer_shell.md`: "русские строки — в одном месте").

export const strings = {
  appTitle: "cs2-modulation",

  setup: {
    heading: "Первый запуск",
    intro: "Программа читает только файлы на диске и ничего не делает с запущенной игрой.",
    gameDirLabel: "Папка CS2",
    gameDirHint: "Подойдёт и корень установки, и путь вида ...\\game\\csgo",
    gameDirPlaceholder: "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Counter-Strike Global Offensive",
    checkButton: "Проверить",
    checking: "Проверяю...",
    gameDirAdjusted: (dir) => `Сохранён путь: ${dir}`,
    gameBuildFound: (build) => `Найден билд игры: ${build}`,
    cacheDirLabel: "Папка кэша (необязательно)",
    cacheDirHint: "Куда сохранять извлечённые данные карт; по умолчанию рядом с программой.",
    cacheDirPlaceholder: "оставьте пустым, чтобы использовать путь по умолчанию",
    saveCacheButton: "Сохранить",
    restartRequired: "Новый путь к кэшу заработает после перезапуска cs2mod serve.",
    cacheDirSaved: "Сохранено.",
    continueButton: "Продолжить",
  },

  maps: {
    heading: "Карты",
    backToSetup: "Настройки",
    columnMap: "Карта",
    columnBuild: "Билд",
    geometry: "геометрия",
    standSpots: "точки стояния",
    radar: "радар",
    staleNoGameDir: "кэш не сверен с установленной игрой",
    staleWrongBuild: "кэш от другого билда игры",
    reextractButton: "Переизвлечь",
    prepareButton: "Подготовить",
    cancelButton: "Отменить",
    openButton: "Открыть",
    noMaps: "Нет ни одной подготовленной карты.",
    extractNewLabel: "Извлечь карту",
    extractNamePlaceholder: "de_mirage",
    extractButton: "Извлечь",
    stageExtract: "извлечение",
    stageStandspots: "точки стояния",
    stageViewerdata: "радар",
    stageQueued: "в очереди",
    stageDone: "готово",
    loading: "Загрузка карт...",
    pillOk: "✓",
    pillMissing: "—",
  },

  mapScreen: {
    backToList: "к списку карт",
    targetHint: "Клик по карте ставит цель, правый клик - точку броска.",
    targetLabel: "Цель",
    targetNone: "Цель не выбрана.",
    levelsHeading: "Несколько высот в этой точке - выберите нужную",
    levelUnnamed: "без названия",
    manualLabel: "Вставить из консоли (setpos ...)",
    manualPlaceholder: "setpos x y z; setang pitch yaw 0",
    manualButton: "Применить",
    manualBad: "Не удалось разобрать строку setpos.",
    noFloorHere: "В этой точке нет пола - выберите другое место.",
  },

  solveParams: {
    heading: "Параметры",
    grenadeLabel: "Граната",
    grenadeSmoke: "Смок",
    grenadeFlash: "Вспышка",
    grenadeHe: "Осколочная",
    grenadeMolotov: "Зажигательная",
    grenadeDecoy: "Обманка",
    grenadeComingSoon: "появится на этапе 7",
    scopeLabel: "Откуда бросать",
    scopeAll: "по всей карте",
    scopeSpawns: "со спавнов",
    scopePoint: "из точки (правый клик по карте)",
    scopePointOption: "из отмеченной точки",
    originReachLabel: "Радиус, ед.",
    toleranceLabel: "Допуск, ед.",
    minStabilityLabel: "Мин. стабильность",
    fineScanLabel: "Подробный поиск",
    typesLabel: "Типы бросков",
    typeStand: "стоя",
    typeCrouch: "присев",
    typeJumpThrow: "прыжком",
    typeCrouchJumpThrow: "присев + прыжок",
    typeRunJumpThrow: "с разбега прыжком",
    strengthsLabel: "Клики",
    strength1: "левой кнопкой",
    strengthHalf: "левой и правой",
    strength0: "правой кнопкой",
    brokenLabel: "Разрушения",
    brokenGlass: "стекло разбито",
    brokenDoors: "двери открыты",
  },

  solve: {
    runButton: "Найти раскидки",
    cancelButton: "Отменить",
    needTarget: "Сначала выберите цель на карте.",
    needTypes: "Выберите хотя бы один тип броска.",
    needStrengths: "Выберите хотя бы один клик.",
    elapsed: (s) => `${s.toFixed(1)} с`,
    checkedCount: (n) => `проверено: ${n}`,
    verifiedCount: (n) => `найдено: ${n}`,
    cachedResult: "Ответ из кэша.",
    emptyHint: "Можно ослабить допуск (tolerance) или расширить область, откуда допустим бросок.",
    phases: {
      queued: "в очереди",
      prepare: "подготовка",
      colliders: "подготовка коллизий",
      origins: "перебор позиций",
      "pinned-origins": "точки у стен",
      "after-pins": "после точек у стен",
      sweep: "перебор бросков",
      verify: "проверка кандидатов",
      exhaustive: "полный перебор",
      escalate: "уточнение",
      "escalate-fine": "точное уточнение",
      sightline: "проверка видимости",
      pins: "точки прицеливания",
      "progress-truncated": "поток точек урезан (слишком много)",
    },
  },

  panel: {
    heading: "Раскидки",
    count: (n) => `найдено: ${n}`,
    stableOnly: "только стабильные",
    hiddenOnly: "только скрытые",
    typeAll: "все типы",
    typeFilterLabel: "Фильтр по типу броска",
    distance: "расстояние",
    stability: "стабильность",
    humanError: "погрешность",
    bounces: "отскоков",
    flightTime: "время полёта",
    pinCorner: "угол",
    pinWall: "стена",
    exposedYes: "виден",
    exposedNo: "скрыт",
    copyButton: "Скопировать",
    copied: "скопировано",
    copyFallback: "Строка выделена - нажмите Ctrl+C.",
    emptyReasonPrefix: "Ничего не найдено",
  },

  errors: {
    serverDown: "Сервер cs2mod serve не отвечает.",
    streamBroken: "Соединение с задачей прервалось. Переподключиться?",
    reconnectButton: "Переподключиться",
    retryButton: "Повторить",
    genericPrefix: "Ошибка",
  },

  theme: {
    toggleToDark: "Тёмная тема",
    toggleToLight: "Светлая тема",
  },
};
